### ISSUE TITLE
F5 - refresh content not page?

### ISSUE THREAD

**Issue by only1pj** [mrbeam/OctoPrint#50]
When the convert progress bar fails, the user can cancel the screen and select the work library to see if there is a new file generated in the background. F5 refreshes the whole web interface instead of just the file list.
Is there a way to reload the file list to check for new files instead of reloading the whole web interface and having to accept the user agreement each time.
"updating firmware" also flashed under the startup warning screen - is this normal?

**Comment by make-ing** [comment]
Hello only1pj,
i don't think it is possible to intercept the F5 page refresh, and even when its possible i don't want to implement it in this way. you should not be forced to reload the file list at all.

The flashing of "updating firmware" is normal since it have to load all the elements and after it finishes loading it hides the elements which are not necessary.
